name: PR version
on:
  pull_request:
        types: [open, reopen, synchronize, label, unlabel]
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump VERSION 
      uses: WiktorJ/update-version-file-on-pr-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

